os: osx
language: node_js
node_js: node
compiler: clang
before_script:
- git checkout package-lock.json
env:
  global:
    - LIBGL_DEBUG=verbose
    #- FILAMENT_REQUIRES_CXXABI=true
script:
- ./scripts/ci-update-screenshots.sh
#- ./scripts/ci-run-tests.sh
cache:
  ccache: true
  directories:
  - node_modules
